apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
   name: com-gabhasti-product-ux
spec:
   selector:
      matchLabels:
         app: com-gabhasti-product-ux # a lable to match with other services(Objects eg: Service)
   replicas: 2 # tells deployment to run 2 pods matching the template
   template:
      metadata:
         labels:
            app: com-gabhasti-product-ux
      spec:
         containers:
         -  name: com-gabhasti-product-ux
            image: gabhastiharishscf/com-gabhasti-product-ux:1.0.0
            imagePullPolicy: Always
            ports:
            -  containerPort: 8081
            
            resources:
               limits:
                  memory: 200Mi
               requests:
                  cpu: 100m
                  memory: 100Mi
            env:
            -  name: JAVA_OPTS
               value: -Xmx128m -Xms64m
         imagePullSecrets:
         -  name: gabhastiharishscf      
---
apiVersion: v1
kind: Service
metadata:
   name: com-gabhasti-product-ux
spec:
   type: NodePort
   selector:
      app: com-gabhasti-product-ux
   ports:
   -  protocol: TCP
      port: 80 # the port on which your application will be accessed viz a service  
      targetPort: 8081 # the port number of your application listens to
      name: http