apiVersion: apps/v1
kind: Deployment
metadata:
   name: postgres
spec:
   selector:
      matchLabels:
         app: postgres
   replicas: 1
   template:
      metadata:
         labels:
            app: postgres
      spec:
         containers:
         -  name: postgres
            image: postgres:12.2
            imagePullPolicy: IfNotPresent
            envFrom:
            -  configMapRef:
                  name: postgres-config
            volumeMounts:
            -  mountPath: /var/lib/postgresql/data
               name: postgredb
         volumes:
         -  name: postgredb
            persistentVolumeClaim:
               claimName: postgres-pv-claim
         imagePullSecrets:
         -  name: gabhastiharishscf
         restartPolicy: Always     
---
apiVersion: v1
kind: Service
metadata:
   name: postgres
   labels:
      app: postgres
spec:
   ports:
   -  name: postgres
      port: 5432
      nodePort: 30432
   type: NodePort
   selector:
      app: postgres