apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgre-db
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: postgre-db
    tier: postgreSQL
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
  labels:
    app: postgre-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: postgres-db
spec:
  selector: 
    matchLabels: 
      app: postgres-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-db
        tier: postgreSQL
    spec:
      containers:
        - image: postgres:12.2
          name: postgresql
          env:
            - name: POSTGRES_USER
              value: postgres-db-sit
            - name: POSTGRES_DB
              value: postgres-gabhasti
            - name: POSTGRES_PASSWORD
              value: postgres-db-sit
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - name: postgresql
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresql
          persistentVolumeClaim:
            claimName: postgres-claim