kind: PersistentVolume
apiVersion: v1
metadata:
   name: postgres-pv-volume
   labels:
      type: local
      app: postgres-pv-volume
spec:
   storageClassName: manual
   capacity:
      storage: 1000M
   accessModes:
   - ReadWriteMany
   hostPath: 
     path: "/data/nfs/postgres"
     
     